title: Lester Imperial # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Full-Stack .NET Core Developer
  <br><br>
  Experienced Software Engineer with a demonstrated history of working in the banking industry and IT business processing. 
  Skilled in Software Documentation, C#, Web Applications, and Bootstrap.
  <br><br>
  <a href="https://www.linkedin.com/in/lesterimperial/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
